# Compass to Map: Xaero's edition - Fabric 1.21.11 build
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.19.3
fabric_version=0.141.4+1.21.11

mod_id=compasstomapxaeros
mod_name=Compass to Map: Xaero's Minimap & Explorer's Compass & Nature's Compass Addon
mod_license=MIT
mod_version=0.1.1
mod_group_id=com.kuronami.compasstomapxaeros
mod_authors=KURONAMI
mod_description=Auto-register Explorer's Compass / Nature's Compass discoveries as Xaero's Minimap waypoints (Fabric 1.21.11).

ec_version=aS4au8gn
nc_version=7w8oJxSS
fcap_version=uXrWPsCu
xaeros_minimap_version=Gv2gIQEn
xaeros_worldmap_version=xQ92jpDL
