# Compass to Map: Xaero's edition - Fabric 1.21.8 build
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.3
fabric_version=0.136.1+1.21.8

mod_id=compasstomapxaeros
mod_name=Compass to Map: Xaero's Minimap & Explorer's Compass & Nature's Compass Addon
mod_license=MIT
mod_version=0.1.1
mod_group_id=com.kuronami.compasstomapxaeros
mod_authors=KURONAMI
mod_description=Auto-register Explorer's Compass / Nature's Compass discoveries as Xaero's Minimap waypoints (Fabric 1.21.8).

ec_version=kLvOTDtT
nc_version=8YXpOUsV
fcap_version=YbUUjWdw
xaeros_minimap_version=qkAppprN
xaeros_worldmap_version=OzheLrx0
