org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.8
minecraft_version_range=[1.21.8]
neo_version=21.8.53
loader_version_range=[1,)

mod_id=compasstomapxaeros
mod_name=Compass to Map: Xaero's Minimap & Explorer's Compass & Nature's Compass Addon
mod_license=All Rights Reserved
mod_version=0.1.1
mod_group_id=com.kuronami.compasstomapxaeros

ec_version=aH10R40c
nc_version=H6rdfYL3
xaeros_minimap_version=3028kfKv
xaeros_worldmap_version=tOPHsPnk
