# Compass to Map: Xaero's edition - Fabric 1.21.1
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.10.7-hotspot

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5
fabric_version=0.116.11+1.21.1

mod_id=compasstomapxaeros
mod_name=Compass to Map: Xaero's Minimap & Explorer's Compass & Nature's Compass Addon
mod_license=All Rights Reserved
mod_version=0.1.1
mod_group_id=com.kuronami.compasstomapxaeros
mod_authors=KURONAMI
mod_description=Auto-register Explorer's Compass / Nature's Compass discoveries as Xaero's Minimap waypoints (Fabric 1.21.1).

ec_version=1.21.1-2.6.0-fabric
nc_version=1.21.1-2.6.0-fabric
fcap_version=v21.1.6-1.21.1-Fabric
xaeros_minimap_version=Y6UMYlPY
xaeros_worldmap_version=HvYNIyXh
